# Generated by Django 3.1.3 on 2020-12-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=250)),
                ('IP', models.CharField(max_length=250)),
                ('num_visits', models.CharField(max_length=250)),
                ('urlsREFERER', models.CharField(max_length=250)),
                ('useragent', models.CharField(max_length=250)),
            ],
        ),
    ]
