# Generated by Django 3.1.3 on 2020-12-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0036_subnavigator_pictures'),
        ('visits', '0004_visitors_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, help_text='Описание проблемы', null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('metka', models.ForeignKey(blank=True, help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='standart.metka', verbose_name='Основное меню')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
    ]
