# Generated by Django 3.1.3 on 2020-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lead',
            field=models.BooleanField(default=False),
        ),
    ]
