# Generated by Django 3.1.3 on 2020-12-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_auto_20201205_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
