# Generated by Django 3.1.3 on 2020-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='Login',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
