# Generated by Django 3.1.3 on 2020-12-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visitors',
            field=models.ForeignKey(blank=True, help_text='привязка к Visitors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='visits.visitors', verbose_name='Visitors'),
        ),
    ]
