# Generated by Django 3.1.3 on 2020-12-16 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_order_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='visitors',
            field=models.ForeignKey(blank=True, help_text='привязка к Visitors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='visits.visitors', verbose_name='Visitors'),
        ),
    ]
