# Generated by Django 3.1.3 on 2020-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_auto_20201216_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
