# Generated by Django 3.1.3 on 2020-12-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0017_order_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
