# Generated by Django 3.1.3 on 2020-12-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='lastupdate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
