# Generated by Django 3.1.3 on 2020-12-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitors_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='IDsession',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
