# Generated by Django 3.1.3 on 2020-12-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_order_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
