# Generated by Django 3.1.3 on 2020-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_auto_20201205_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
