# Generated by Django 3.1.3 on 2020-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0015_auto_20201216_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
