# Generated by Django 3.1.3 on 2020-11-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0002_auto_20201117_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_c',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_c',
        ),
    ]
