# Generated by Django 3.1.3 on 2020-11-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0008_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='название темплейта', max_length=30, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Template',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='template_name',
            field=models.ForeignKey(blank=True, help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='standart.templates', verbose_name='Основное меню'),
        ),
    ]
