# Generated by Django 3.1.3 on 2020-11-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0010_auto_20201121_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='subname',
        ),
    ]
