# Generated by Django 3.1.3 on 2020-11-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0013_auto_20201121_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='pictures',
            field=models.ManyToManyField(to='standart.Pictures'),
        ),
    ]
