# Generated by Django 3.1.3 on 2020-11-21 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0014_text_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='pictures',
        ),
        migrations.AddField(
            model_name='text',
            name='pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standart.pictures'),
        ),
    ]
