# Generated by Django 3.1.3 on 2020-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0016_auto_20201125_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='image',
            field=models.ImageField(blank=True, upload_to='material-kit-master/products'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='width',
            field=models.IntegerField(blank=True, default=600, help_text='название раздела', verbose_name='ширина'),
        ),
    ]
