# Generated by Django 3.1.3 on 2020-12-02 14:35

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0019_auto_20201130_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nexamples', to='standart.navconstruct', verbose_name='Основное меню')),
                ('subname', models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexamples', to='standart.subnavigator', verbose_name='Подменю')),
            ],
            options={
                'verbose_name': 'Тип блока',
                'verbose_name_plural': 'Тип блока',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='container',
            name='examples',
            field=models.ForeignKey(blank=True, help_text='привязка к примеру', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='standart.examples', verbose_name='Прмиер'),
        ),
        migrations.CreateModel(
            name='ExamplesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='название раздела', max_length=30, verbose_name='Наименование')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='standart.examples')),
            ],
            options={
                'verbose_name': 'Тип блока Translation',
                'db_table': 'standart_examples_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
