# Generated by Django 3.1.3 on 2020-12-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0032_subnavigator_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navconstruct',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subnavigator',
            name='section',
        ),
    ]
