# Generated by Django 3.1.3 on 2020-12-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0035_navconstruct_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnavigator',
            name='pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpict', to='standart.pictures'),
        ),
    ]
