# Generated by Django 3.1.3 on 2020-12-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0048_auto_20201216_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='examples',
            field=models.ForeignKey(blank=True, help_text='привязка к примеру', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example', to='standart.examples', verbose_name='Пример'),
        ),
    ]
