# Generated by Django 3.1.3 on 2020-11-18 20:10

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0003_auto_20201117_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navconstruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='последователность отображения в меню', null=True, verbose_name='Порядок в меню')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Основное меню',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subnavigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.ForeignKey(blank=True, help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='standart.navconstruct', verbose_name='Основное меню')),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подменю',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubnavigatorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='название основного раздела', max_length=200, verbose_name='Название раздела')),
                ('slug', models.SlugField(blank=True, help_text='название url адреса', max_length=200, null=True, unique=True, verbose_name='URL адрес')),
                ('section', models.TextField(help_text='название секции, необязательно', null=True, verbose_name='Название секции')),
                ('hreflogo', models.CharField(blank=True, help_text='URL картинка', max_length=100, verbose_name='URL картинка')),
                ('alt', models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка')),
                ('title', models.CharField(blank=True, help_text='описание заголовка в строке браузера', max_length=300, verbose_name='Заголовок')),
                ('descrtionmeta', models.TextField(blank=True, help_text='описание страницы в поискаовика', max_length=300, verbose_name='Описание страницы')),
                ('keywordsmeta', models.TextField(blank=True, help_text='ключевые слова для поисковика', max_length=300, verbose_name='Ключевые слова')),
                ('template_name', models.CharField(help_text='название html файла', max_length=30, null=True, verbose_name='Название html')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='standart.subnavigator')),
            ],
            options={
                'verbose_name': 'Подраздел Translation',
                'db_table': 'standart_subnavigator_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NavconstructTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='название основного раздела', max_length=200, verbose_name='Название раздела')),
                ('slug', models.SlugField(blank=True, help_text='название url адреса', max_length=200, null=True, unique=True, verbose_name='URL адрес')),
                ('section', models.TextField(help_text='название секции, необязательно', null=True, verbose_name='Название секции')),
                ('hreflogo', models.CharField(blank=True, help_text='URL картинка', max_length=100, verbose_name='URL картинка')),
                ('alt', models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка')),
                ('title', models.CharField(blank=True, help_text='описание заголовка в строке браузера', max_length=300, verbose_name='Заголовок')),
                ('descrtionmeta', models.TextField(blank=True, help_text='описание страницы в поискаовика', max_length=300, verbose_name='Описание страницы')),
                ('keywordsmeta', models.TextField(blank=True, help_text='ключевые слова для поисковика', max_length=300, verbose_name='Ключевые слова')),
                ('template_name', models.CharField(help_text='название html файла', max_length=30, null=True, verbose_name='Название html')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='standart.navconstruct')),
            ],
            options={
                'verbose_name': 'Раздел Translation',
                'db_table': 'standart_navconstruct_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
