# Generated by Django 3.1.3 on 2020-11-20 13:28

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0004_navconstruct_navconstructtranslation_subnavigator_subnavigatortranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='последователность отображения на странице', null=True, verbose_name='Порядок на странице')),
                ('name', models.ForeignKey(blank=True, help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntext', to='standart.navconstruct', verbose_name='Основное меню')),
                ('subname', models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stext', to='standart.navconstruct', verbose_name='Основное меню')),
            ],
            options={
                'verbose_name': 'Информация страницы',
                'verbose_name_plural': 'Информация страницы',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='название раздела', max_length=30, verbose_name='Наименование')),
                ('text', models.TextField(blank=True, help_text='описание', verbose_name='Текст')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='standart.text')),
            ],
            options={
                'verbose_name': 'Информация страницы Translation',
                'db_table': 'standart_text_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
