# Generated by Django 3.1.3 on 2020-11-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0005_text_texttranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnavigatortranslation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='text',
            name='subname',
            field=models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stext', to='standart.subnavigator', verbose_name='Подменю'),
        ),
    ]
