# Generated by Django 3.1.3 on 2020-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0006_auto_20201121_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnavigatortranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='название url адреса', max_length=200, null=True, unique=True, verbose_name='URL адрес'),
        ),
    ]
