# Generated by Django 3.1.3 on 2020-11-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0007_subnavigatortranslation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='название раздела', max_length=30, verbose_name='Наименование')),
                ('order', models.IntegerField(blank=True, help_text='последователность отображения на странице', null=True, verbose_name='Порядок на странице')),
                ('name', models.ForeignKey(blank=True, help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncont', to='standart.navconstruct', verbose_name='Основное меню')),
                ('subname', models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scont', to='standart.subnavigator', verbose_name='Подменю')),
            ],
            options={
                'verbose_name': 'Тип блока',
                'verbose_name_plural': 'Тип блока',
            },
        ),
    ]
