# Generated by Django 3.1.3 on 2020-11-21 23:14

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0012_remove_text_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Картинки страницы',
                'verbose_name_plural': 'Картинки страницы',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['order'], 'verbose_name': 'Тип блока', 'verbose_name_plural': 'Тип блока'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['order'], 'verbose_name': 'Информация страницы', 'verbose_name_plural': 'Информация страницы'},
        ),
        migrations.CreateModel(
            name='PicturesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('alt', models.CharField(db_index=True, max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='standart.pictures')),
            ],
            options={
                'verbose_name': 'Картинки страницы Translation',
                'db_table': 'standart_pictures_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
