# Generated by Django 3.1.3 on 2020-11-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0017_auto_20201125_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='height',
            field=models.IntegerField(blank=True, default=600, help_text='название раздела', verbose_name='высота'),
        ),
    ]
