# Generated by Django 3.1.3 on 2020-12-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0021_auto_20201202_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='examples',
            field=models.ForeignKey(blank=True, help_text='привязка к примеру', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='standart.examples', verbose_name='Пример'),
        ),
    ]
