# Generated by Django 3.1.3 on 2020-12-03 09:54

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0027_navconstruct_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='последователность отображения на странице', null=True, verbose_name='Порядок на странице')),
                ('container', models.ForeignKey(blank=True, help_text='привязка к Templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contable', to='standart.container', verbose_name='Templates')),
                ('pictures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='standart.pictures')),
            ],
            options={
                'verbose_name': 'Информация таблицы',
                'verbose_name_plural': 'Информация таблицы',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='navconstruct',
            name='table',
            field=models.BooleanField(default=False, help_text='наличие таблицы', verbose_name='Наличие таблицы'),
        ),
        migrations.CreateModel(
            name='TableTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True, help_text='описание', verbose_name='Текст')),
                ('one', models.TextField(blank=True, help_text='описание', verbose_name='Текст')),
                ('two', models.TextField(blank=True, help_text='описание', verbose_name='Текст')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='standart.table')),
            ],
            options={
                'verbose_name': 'Информация таблицы Translation',
                'db_table': 'standart_table_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
