# Generated by Django 3.1.3 on 2020-12-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0029_table_picturesvs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navconstruct',
            name='table',
        ),
        migrations.RemoveField(
            model_name='navconstructtranslation',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subnavigatortranslation',
            name='section',
        ),
    ]
