# Generated by Django 3.1.3 on 2020-12-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0030_auto_20201203_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='navconstruct',
            name='section',
            field=models.ForeignKey(blank=True, help_text='привязка к TemplatesSections', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='standart.templates', verbose_name='Sections'),
        ),
    ]
