# Generated by Django 3.1.3 on 2020-12-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0031_navconstruct_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnavigator',
            name='section',
            field=models.ForeignKey(blank=True, help_text='привязка к TemplatesSections', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsection', to='standart.templates', verbose_name='Sections'),
        ),
    ]
