# Generated by Django 3.1.3 on 2020-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0033_auto_20201203_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='description',
            field=models.TextField(blank=True, help_text='описание', null=True, verbose_name='Текст'),
        ),
    ]
