# Generated by Django 3.1.3 on 2020-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0037_navconstruct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnavigator',
            name='status',
            field=models.CharField(choices=[('odinary', 'Odinary'), ('form', 'Form'), ('call', 'Call'), ('service', 'Service'), ('example', 'Example')], default='odinary', max_length=10),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='status',
            field=models.CharField(choices=[('odinary', 'Odinary'), ('form', 'Form'), ('call', 'Call'), ('service', 'Service'), ('example', 'Example')], default='odinary', max_length=10),
        ),
    ]
