# Generated by Django 3.1.3 on 2020-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0038_auto_20201214_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navconstruct',
            name='status',
            field=models.CharField(choices=[('odinary', 'Odinary'), ('form', 'Form'), ('call', 'Call'), ('service', 'Service'), ('example', 'Example'), ('login', 'Login')], default='odinary', max_length=10),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='status',
            field=models.CharField(choices=[('odinary', 'Odinary'), ('form', 'Form'), ('call', 'Call'), ('service', 'Service'), ('example', 'Example'), ('login', 'Login')], default='odinary', max_length=10),
        ),
    ]
