# Generated by Django 3.1.3 on 2020-12-15 11:38

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0039_auto_20201215_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templatecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Название категории',
                'verbose_name_plural': 'Категории',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='navconstruct',
            name='bar',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='first', max_length=10),
        ),
        migrations.CreateModel(
            name='TemplatecategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='standart.templatecategory')),
            ],
            options={
                'verbose_name': 'Название категории Translation',
                'db_table': 'standart_templatecategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
