# Generated by Django 3.1.3 on 2020-12-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0040_auto_20201215_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='navconstruct',
            name='newslug',
            field=models.ForeignKey(blank=True, help_text='название url адреса', null=True, on_delete=django.db.models.deletion.CASCADE, to='standart.templatecategory', verbose_name='URL'),
        ),
    ]
