# Generated by Django 3.1.3 on 2020-12-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0041_navconstruct_newslug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'verbose_name': 'Название категории', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.AddField(
            model_name='navconstruct',
            name='newsslug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsslug', to='standart.templatecategory', verbose_name='Второе меню'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='newslug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newslug', to='standart.templatecategory', verbose_name='Первое меню'),
        ),
    ]
