# Generated by Django 3.1.3 on 2020-12-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0043_auto_20201215_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='status',
            field=models.CharField(choices=[('odinary', 'Odinary'), ('form', 'Form'), ('call', 'Call'), ('service', 'Service')], default='odinary', max_length=10),
        ),
    ]
