# Generated by Django 3.1.3 on 2020-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0047_auto_20201216_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navconstructtranslation',
            name='title',
            field=models.CharField(blank=True, help_text='описание заголовка в строке браузера', max_length=300, verbose_name='Заголовок'),
        ),
    ]
