# Generated by Django 3.1.3 on 2020-12-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0050_navconstruct_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='navconstruct',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='разделы на странице', related_name='category', to='standart.Category'),
        ),
        migrations.AlterField(
            model_name='navconstructtranslation',
            name='alt',
            field=models.TextField(blank=True, help_text='текст блока если данные отправлены неверно', max_length=300, verbose_name='Текст блока если данные отправлены неверно'),
        ),
        migrations.AlterField(
            model_name='navconstructtranslation',
            name='hreflogo',
            field=models.TextField(blank=True, help_text='текст блока успешного сообщения', max_length=100, verbose_name='Текст блока успешного сообщения'),
        ),
    ]
