# Generated by Django 3.1.3 on 2020-12-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0051_auto_20201222_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
