# Generated by Django 3.1.3 on 2020-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standart', '0053_auto_20201222_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, help_text='последователность отображения в меню', null=True, verbose_name='Порядок в меню'),
        ),
    ]
